server:
  port: 8082
  
spring:
  data:
    mongodb:
      uri:  mongodb+srv://raju:raju@carwash.ayvtn.mongodb.net/customer?retryWrites=true&w=majority
      
  application:
    name: Customer-Service
